task-3
ozoncp/ocp-requirement-api pull request #3
Opened 2021-07-24 19:17 UTC by yetanotherjsontodatabaseexporter

…were added.

2021-07-26 14:55 UTC, MrDniwe requested changes
Принципиальных проблем не вижу, разве что небольшую правку по логике батчинга

2021-07-26 14:55 UTC, MrDniwe commented on internal/utils/requirement.go
> +	}
Спорный момент. Я бы скорее сказал, что в таком случае нужно возвращать "сколько есть".  По сути эта задача о пагинации. И если у тебя пагинация "по 50 на страницу", а элементов всего 10, то и отдавать надо имеющиеся 10.

2021-07-26 16:12 UTC, yetanotherjsontodatabaseexporter commented on internal/utils/requirement.go
> +	}
Согласен

2021-07-27 07:13 UTC, MrDniwe approved these changes

2021-07-27 09:03 UTC, merged